import { ChallengeDefinition } from '../models';

export const cliFilesChallenges: ChallengeDefinition[] = [
  {
    id: 'cli-cat-01',
    kind: 'shell',
    category: 'files',
    tier: 1,
    title: 'Display a file',
    prompt: 'Use cat to print the latency dataset.',
    goal: 'Show the full contents of latency.csv in /home/lab.',
    hints: ['cat reads a file and writes it to stdout.', 'Try: cat latency.csv'],
    shell: {
      commandIncludes: ['cat'],
      expectedStdoutContains: ['timestamp,endpoint,ping_min', 'portal-a'],
      validationMode: 'contains',
    },
  },
  {
    id: 'cli-head-01',
    kind: 'shell',
    category: 'files',
    tier: 1,
    title: 'First lines with head',
    prompt: 'Show only the header row and first data row.',
    goal: 'Use head -n 2 on latency.csv.',
    hints: ['head -n N prints the first N lines.', 'Files are in the current directory /home/lab.'],
    shell: {
      commandIncludes: ['head'],
      expectedStdoutLines: [
        'timestamp,endpoint,ping_min,ping_avg,ping_max,http_ms,http_status',
        '2026-09-27T08:00:00,portal-a,31.2,35.6,41.1,182,200',
      ],
      orderedLines: true,
      validationMode: 'exact',
    },
  },
  {
    id: 'cli-tail-01',
    kind: 'shell',
    category: 'files',
    tier: 1,
    title: 'Last lines with tail',
    prompt: 'Inspect the most recent measurements.',
    goal: 'Use tail -n 3 on latency.csv to see the last three lines.',
    hints: ['tail -n 3 shows the final three lines.', 'Useful for recent log entries.'],
    shell: {
      commandIncludes: ['tail'],
      expectedStdoutContains: ['portal-c,63.8,71.5', 'portal-b,42.5,48.0', 'portal-a,32.1,36.9'],
      validationMode: 'contains',
    },
  },
  {
    id: 'cli-wc-01',
    kind: 'shell',
    category: 'files',
    tier: 2,
    title: 'Count lines with wc',
    prompt: 'How many lines are in the dataset (including the header)?',
    goal: 'Use wc -l latency.csv and observe the line count.',
    hints: ['wc -l counts newline-separated lines.', 'The CSV has a header plus data rows.'],
    shell: {
      commandIncludes: ['wc'],
      expectedStdout: '16',
      validationMode: 'exact',
    },
  },
  {
    id: 'cli-less-01',
    kind: 'shell',
    category: 'files',
    tier: 2,
    title: 'Page through a log',
    prompt: 'Open latency.log with less to preview a long file.',
    goal: 'Run less latency.log (simulated first screen).',
    hints: ['less lets you scroll large files interactively.', 'On real systems, q quits less.'],
    shell: {
      commandIncludes: ['less'],
      expectedStdoutContains: ['ping_avg=', 'portal-a'],
      validationMode: 'contains',
    },
  },
  {
    id: 'cli-cut-01',
    kind: 'shell',
    category: 'files',
    tier: 2,
    title: 'Extract a CSV column',
    prompt: 'Print only the endpoint column from latency.csv.',
    goal: 'Use cut -d, -f2 latency.csv and include the header endpoint value.',
    hints: ['-d, sets comma as the delimiter.', '-f2 selects the second field.'],
    shell: {
      commandIncludes: ['cut'],
      expectedStdoutContains: ['endpoint', 'portal-a', 'portal-b', 'portal-c'],
      validationMode: 'contains',
    },
  },
];
