import { ChallengeDefinition } from '../models';

export const cliSystemChallenges: ChallengeDefinition[] = [
  {
    id: 'cli-ps-01',
    kind: 'shell',
    category: 'system',
    tier: 3,
    title: 'Process list',
    prompt: 'See which monitoring commands are running on a constrained host.',
    goal: 'Run ps aux (or ps -ef).',
    hints: ['ps shows active processes.', 'Look for ping and curl in the output.'],
    shell: {
      commandIncludes: ['ps'],
      expectedStdoutContains: ['ping portal-a.example.com', 'curl -s https://portal-a.example.com'],
      validationMode: 'contains',
    },
  },
  {
    id: 'cli-df-01',
    kind: 'shell',
    category: 'system',
    tier: 3,
    title: 'Disk space',
    prompt: 'Check filesystem usage in human-readable units.',
    goal: 'Run df -h.',
    hints: ['df reports mounted filesystem capacity.', '-h prints KB/MB/GB suffixes.'],
    shell: {
      commandIncludes: ['df', '-h'],
      expectedStdoutContains: ['Filesystem', '/dev/vda1', 'Mounted on'],
      validationMode: 'contains',
    },
  },
  {
    id: 'cli-du-01',
    kind: 'shell',
    category: 'system',
    tier: 3,
    title: 'Directory size',
    prompt: 'Estimate how much space the lab directory uses.',
    goal: 'Run du -h . from /home/lab.',
    hints: ['du summarizes file sizes under a path.', 'Helpful before shipping logs off-box.'],
    shell: {
      commandIncludes: ['du'],
      expectedStdoutContains: ['/home/lab'],
      validationMode: 'contains',
    },
  },
  {
    id: 'cli-free-01',
    kind: 'shell',
    category: 'system',
    tier: 3,
    title: 'Memory usage',
    prompt: 'Check available memory on the monitoring host.',
    goal: 'Run free -h.',
    hints: ['free shows RAM and swap.', 'Low available memory can slow HTTP responses.'],
    shell: {
      commandIncludes: ['free', '-h'],
      expectedStdoutContains: ['Mem:', 'available'],
      validationMode: 'contains',
    },
  },
  {
    id: 'cli-ssh-01',
    kind: 'shell',
    category: 'system',
    tier: 4,
    title: 'Remote shell (simulated)',
    prompt: 'Connect to the monitoring jump host.',
    goal: 'Run ssh monitor.lab (simulated — no real remote access).',
    hints: ['ssh opens an encrypted remote session.', 'This lab simulates the handshake message only.'],
    shell: {
      commandIncludes: ['ssh'],
      expectedStdoutContains: ['Connected to monitor.lab'],
      validationMode: 'contains',
    },
  },
  {
    id: 'cli-scp-01',
    kind: 'shell',
    category: 'system',
    tier: 4,
    title: 'Copy logs remotely (simulated)',
    prompt: 'Copy latency.csv to a backup server.',
    goal: 'Run scp latency.csv backup.lab:/data/latency.csv.',
    hints: ['scp uses SSH under the hood.', 'Common for moving logs without extra tools.'],
    shell: {
      commandIncludes: ['scp', 'latency.csv'],
      expectedStdoutContains: ['simulated copy complete'],
      validationMode: 'contains',
    },
  },
];
