import { ChallengeDefinition } from '../models';

export const cliPipelineChallenges: ChallengeDefinition[] = [
  {
    id: 'cli-pipe-01',
    kind: 'shell',
    category: 'pipelines',
    tier: 3,
    title: 'First pipe',
    prompt: 'Stream the log file into grep instead of naming the file twice.',
    goal: 'cat latency.log | grep portal-a',
    hints: ['The left command produces stdout; the right command reads it as stdin.', 'Same result as grep portal-a latency.log.'],
    shell: {
      commandIncludes: ['|', 'cat', 'grep'],
      showPipeline: true,
      expectedStdoutContains: ['portal-a', 'ping_avg='],
      validationMode: 'contains',
    },
  },
  {
    id: 'cli-pipe-02',
    kind: 'shell',
    category: 'pipelines',
    tier: 4,
    title: 'Filter then cut',
    prompt: 'From the CSV, keep portal-b rows and print ping_avg values only.',
    goal: 'grep portal-b latency.csv | cut -d, -f4',
    hints: ['grep filters rows; cut selects columns.', 'ping_avg is field 4.'],
    shell: {
      commandIncludes: ['|'],
      showPipeline: true,
      expectedStdoutLines: ['48.7', '47.2', '46.1', '49.5', '48.0'],
      orderedLines: true,
      validationMode: 'exact',
    },
  },
  {
    id: 'cli-pipe-03',
    kind: 'shell',
    category: 'pipelines',
    tier: 4,
    title: 'Three-stage pipeline',
    prompt: 'Average HTTP latency for portal-c using grep, awk, and implied aggregation.',
    goal: 'grep portal-c latency.csv | awk -F, \'{sum += $6; n++} END {print sum/n}\'',
    hints: ['Each stage passes text to the next.', 'Field 6 is http_ms.'],
    shell: {
      commandIncludes: ['grep', 'awk', '|'],
      showPipeline: true,
      expectedStdoutPattern: '^314$',
      validationMode: 'regex',
    },
  },
  {
    id: 'cli-pipe-04',
    kind: 'shell',
    category: 'pipelines',
    tier: 5,
    title: 'Sort a pipeline',
    prompt: 'List portal-a ping_avg values sorted numerically.',
    goal: 'grep portal-a latency.csv | awk -F, \'{print $4}\' | sort -n',
    hints: ['This is the classic filter → transform → sort workflow.', 'sort -n must be last.'],
    shell: {
      commandIncludes: ['sort', '-n', '|'],
      showPipeline: true,
      expectedStdoutLines: ['34.2', '35.6', '36.9', '38.1', '52.8'],
      orderedLines: true,
      validationMode: 'exact',
    },
  },
  {
    id: 'cli-pipe-05',
    kind: 'shell',
    category: 'pipelines',
    tier: 5,
    title: 'Count elevated HTTP latency',
    prompt: 'How many portal-a observations have http_ms above 200?',
    goal: 'grep portal-a latency.csv | awk -F, \'$6 > 200 {n++} END {print n}\'',
    hints: ['awk can filter with expressions like $6 > 200.', 'END {print n} reports the count.'],
    shell: {
      commandIncludes: ['awk', '|'],
      showPipeline: true,
      expectedStdout: '1',
      validationMode: 'exact',
    },
  },
];
