import { ChallengeDefinition } from '../models';

export const cliTextChallenges: ChallengeDefinition[] = [
  {
    id: 'cli-sort-01',
    kind: 'shell',
    category: 'text',
    tier: 3,
    title: 'Numeric sort',
    prompt: 'Sort ping average values for portal-a from lowest to highest.',
    goal: 'grep portal-a latency.csv | awk -F, \'{print $4}\' | sort -n',
    hints: ['sort -n compares numbers, not text.', 'Extract the ping_avg column first (field 4).'],
    shell: {
      commandIncludes: ['sort', '-n'],
      expectedStdoutLines: ['34.2', '35.6', '36.9', '38.1', '52.8'],
      orderedLines: true,
      validationMode: 'exact',
    },
  },
  {
    id: 'cli-uniq-01',
    kind: 'shell',
    category: 'text',
    tier: 3,
    title: 'Unique endpoints',
    prompt: 'List each endpoint once from the CSV (sorted first).',
    goal: 'cut -d, -f2 latency.csv | tail -n +2 | sort | uniq',
    hints: ['uniq only collapses adjacent duplicates — sort first.', 'Skip the header with tail -n +2.'],
    shell: {
      commandIncludes: ['uniq'],
      expectedStdoutLines: ['portal-a', 'portal-b', 'portal-c'],
      orderedLines: true,
      validationMode: 'exact',
    },
  },
  {
    id: 'cli-sed-01',
    kind: 'shell',
    category: 'text',
    tier: 3,
    title: 'Substitute with sed',
    prompt: 'Rename portal-a to PORTAL-A in the log view.',
    goal: 'Use sed to replace portal-a with PORTAL-A in latency.log.',
    hints: ['sed s/old/new/ replaces text per line.', 'Try: sed \'s/portal-a/PORTAL-A/\' latency.log'],
    shell: {
      commandIncludes: ['sed'],
      expectedStdoutContains: ['PORTAL-A'],
      validationMode: 'contains',
    },
  },
  {
    id: 'cli-awk-01',
    kind: 'shell',
    category: 'text',
    tier: 4,
    title: 'Extract a field with awk',
    prompt: 'Print HTTP response times (ms) for portal-a rows.',
    goal: 'grep portal-a latency.csv | awk -F, \'{print $6}\'',
    hints: ['awk -F, treats CSV columns as fields.', 'http_ms is the 6th column.'],
    shell: {
      commandIncludes: ['awk'],
      expectedStdoutLines: ['182', '195', '178', '420', '188'],
      orderedLines: true,
      validationMode: 'exact',
    },
  },
  {
    id: 'cli-awk-02',
    kind: 'shell',
    category: 'text',
    tier: 4,
    title: 'Average with awk',
    prompt: 'Calculate the average ping_avg for portal-a.',
    goal: 'grep portal-a latency.csv | awk -F, \'{sum += $4; n++} END {print sum/n}\'',
    hints: ['END blocks run after all lines.', 'Field 4 is ping_avg in the CSV.'],
    shell: {
      commandIncludes: ['awk'],
      expectedStdoutPattern: '^39\\.52$',
      validationMode: 'regex',
    },
  },
];
